// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCII_AWt_s2ntHyL8-JvukUNtD0IFtbXbo',
    appId: '1:181281971622:android:dc7df27fb14fabb8118367',
    messagingSenderId: '181281971622',
    projectId: 'ecowatt-energy-tracker',
    storageBucket: 'ecowatt-energy-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdQN0VQgr9fcitNg_ixytpgaxQ1YFyTVc',
    appId: '1:181281971622:ios:a484ce7b11844cea118367',
    messagingSenderId: '181281971622',
    projectId: 'ecowatt-energy-tracker',
    storageBucket: 'ecowatt-energy-tracker.firebasestorage.app',
    iosBundleId: 'com.example.ecoWatt',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe-HCnclPBwmlQVqVsUQI9aWKUXS6J9Yg',
    appId: '1:181281971622:web:cbe422e04426a804118367',
    messagingSenderId: '181281971622',
    projectId: 'ecowatt-energy-tracker',
    authDomain: 'ecowatt-energy-tracker.firebaseapp.com',
    storageBucket: 'ecowatt-energy-tracker.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdQN0VQgr9fcitNg_ixytpgaxQ1YFyTVc',
    appId: '1:181281971622:ios:a484ce7b11844cea118367',
    messagingSenderId: '181281971622',
    projectId: 'ecowatt-energy-tracker',
    storageBucket: 'ecowatt-energy-tracker.firebasestorage.app',
    iosBundleId: 'com.example.ecoWatt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe-HCnclPBwmlQVqVsUQI9aWKUXS6J9Yg',
    appId: '1:181281971622:web:3e07ad73a9813ba2118367',
    messagingSenderId: '181281971622',
    projectId: 'ecowatt-energy-tracker',
    authDomain: 'ecowatt-energy-tracker.firebaseapp.com',
    storageBucket: 'ecowatt-energy-tracker.firebasestorage.app',
  );

}